### ISSUE TITLE
add error handling for "device not readable"

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-graphql#24]
If reading from a device and we get back a "device not readable" error, then we should be okay with that. There were previous issues with this because I guess error handling here isn't great and it looked like any other error, so it polluted prometheus with errors.

here, we should check for errors on read and if it is a device not readable error, we simply just shouldn't provide metrics for that device.

I'll update more tomorrow on what the error looks like, etc.

see https://github.com/vapor-ware/synse-cli/issues/162 for more details.

**Comment by edaniszewski** [comment]
[test-plugin.tar.gz](https://github.com/vapor-ware/synse-graphql/files/2123796/test-plugin.tar.gz)
This is a simple test plugin built using v1.0 of the SDK (I can update if that needs to change to master or something)

with that, 
```
$ docker load < test-plugin.tar.gz
```

and you should see the image
```
$ docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
vaporio/test-plugin                        latest              b65c9ad2b145        35 minutes ago      9.82MB
...
```

Then, with this composefile:
```yaml
version: "3"
services:
  synse-graphql:
    container_name: synse-graphql
    image: vaporio/synse-graphql
    ports:
      - 5001:5001
    links:
      - synse-server

  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    ports:
      - 5000:5000
    environment:
      SYNSE_TCP_PLUGIN: test-plugin:5001
    links:
      - test-plugin

  test-plugin:
    container_name: test-plugin
    image: vaporio/test-plugin
    expose:
      - 5001

```
you should be able to start up the plugin w/ synse server (both based off of the sdk1.0 work.. images/tags may need to change here..) and synse-graphql.

The plugin provides four devices:
- read ok: only supports reading, and reads succeed
- write ok: only supports writing, writes succeed (it writes whatever value is in the `Action` field of the data)
- read error: always errors on read
- write error: always errors on writes

This should make it possible to test a case for "device not readable" (e.g. try reading the 'write ok' device) and "device not writable" (writing to the 'read ok' device), as well as seeing what other read/write failures come up as.

There probably needs to be a bit of finagling with the correct images/tags, but i can help out as needed. this plugin setup could also be helpful for bringing synse-graphql up-to-speed with all the new synse server changes.
